version: 2
updates:
  - package-ecosystem: npm
    versioning-strategy: lockfile-only
    directory: /source
    schedule:
      interval: weekly
    labels:
      - dependencies
      - dependabot
      - auto-merge
